# update_record.py
"""
CRUD: Update a student record.
This module will be generated by the code‑generation agent.
It should expose a function that updates a specific record for the
authenticated student, logs the UPDATE SQL via `save_document`, and
returns a success JSON response.
"""

import sqlite3
from document_store import save_document

def update_record(conn: sqlite3.Connection, record_id: int, student_id: int, new_course: str | None = None, new_grade: str | None = None) -> None:
    """Update a record for a student.

    Parameters
    ----------
    conn: sqlite3.Connection
        Active DB connection.
    record_id: int
        ID of the record to update.
    student_id: int
        ID of the student that owns the record (used for safety).
    new_course: str | None
        New course name, if provided.
    new_grade: str | None
        New grade, if provided.
    """
    cur = conn.cursor()
    try:
        # Build dynamic SET clause based on provided fields
        fields = []
        params = []
        if new_course is not None:
            fields.append("course = ?")
            params.append(new_course)
        if new_grade is not None:
            fields.append("grade = ?")
            params.append(new_grade)
        if not fields:
            result = f"[UPDATE_RECORD] No fields to update for record_id={record_id}"
            save_document(result, operation="update_record")
            return
        params.extend([record_id, student_id])
        sql = f"UPDATE records SET {', '.join(fields)} WHERE id = ? AND student_id = ?"
        cur.execute(sql, tuple(params))
        conn.commit()
        if cur.rowcount:
            result = f"[UPDATE_RECORD] Success: record_id={record_id} updated."
        else:
            result = f"[UPDATE_RECORD] Failure: No matching record found for record_id={record_id} and student_id={student_id}."
    except Exception as e:
        result = f"[UPDATE_RECORD] Failure: {e}"
    save_document(result, operation="update_record")
